import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/templates/navbar/Navbar";
import Footer from "./components/templates/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="max-w-screen-xl mx-auto mt-24 min-h-[calc(100vh-100px-150px)]">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
